[build]
publish = "dist/"
command = "npm run build"

[context.production.environment]
NODE_ENV = "production"

[context.deploy-preview.environment]
DEBUG = "url,eleventyComputed"
NODE_ENV = "production"

[[redirects]]
from = "/"
to = "/.netlify/functions/dynamic"
status = 200
force = true
_generated_by_eleventy_serverless = "dynamic"
