[build]
publish = "dist/"
command = "npm run build"

[[redirects]]
from = "/"
to = "/.netlify/functions/dynamic"
status = 200
force = true
_generated_by_eleventy_serverless = "dynamic"

[functions]
included_files = [
  "./netlify/functions/dynamic/**/*",
  "./netlify/functions/dynamic/.cache/**/*"
]
